### PR TITLE
Stricter version pin, some template tweaks, rerender w/ 2.2.2

### PR DESCRIPTION
**Pull request by pmlandwehr**
The CIs seem to be failing because `setup.py` used `distutils.StrictVersion` to verify that `setuptools >=17.1` Since the current version of setuptools used by default is `33.1.1.post20170320`, `StrictVersion` fails to parse the string correctly and the build fails the CIs. Hopefully the maximum pin I put on `setuptools` will solve that.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Unfortunately, local tests show that this pin doesn't have the desired effect - indeed, even `setuptools >=17.1,>=33.1.1,!=33.1.1.post20170320`doesn't have any effect. Not sure what to do next...

**Comment by jakirkham** [comment]
Shouldn't be `>=17.1,<=33.1.1`?

**Comment by jakirkham** [comment]
Also this should be PR'd against `re-render__v1.3.0__2.2.2`.

**Comment by pmlandwehr** [comment]
> Shouldn't it be >=17.1,<=33.1.1?

... that is what it is, I think?

**Pull request closed without merging**
